jobs:
  valid_json:
    docker:
    - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - run:
          name: Setup
          shell: /bin/bash
          command: |
            sudo apt-get update
            sudo apt-get install jsonlint
      - run:
          name: Checking JSON syntax
          shell: /bin/bash
          command: |
            find |grep "\.json$" |jsonlint-php
workflows:
  version: 2
  test:
    jobs:
    - valid_json
version: 2
