jobs:
  valid_json:
    docker:
    - image: bash:4.4.19
    steps:
    - checkout
    - run:apt install jsonlint
    - run:ls -R |grep "\.json$" |jsonlint
workflows:
  version: 2
  test:
    jobs:
    - valid_json
version: 2
