jobs:
  valid_json:
    docker:
    - image: bash:4.4.19
    steps:
      - checkout
      - run:
          name: Setup
          shell: /bin/bash
          command: |
            apt-get update
            apt-get install jsonlint
      - run:
          name: Checking JSON syntax
          shell: /bin/bash
          command: |
            find |grep "\.json$" |jsonlint
workflows:
  version: 2
  test:
    jobs:
    - valid_json
version: 2
